/* Automatically generated by './build/build-components-entry.js' */

import { default as MazArrowIcon } from './MazArrowIcon.vue.vue'
import { default as MazAvatar } from './MazAvatar.vue.vue'
import { default as MazBackDrop } from './MazBackDrop.vue.vue'
import { default as MazBottomSheet } from './MazBottomSheet.vue.vue'
import { default as MazBtn } from './MazBtn.vue.vue'
import { default as MazCard } from './MazCard.vue.vue'
import { default as MazCheckbox } from './MazCheckbox.vue.vue'
import { default as MazDialog } from './MazDialog.vue.vue'
import { default as MazDropzone } from './MazDropzone.vue.vue'
import { default as MazGallery } from './MazGallery.vue.vue'
import { default as MazIcon } from './MazIcon.vue.vue'
import { default as MazInput } from './MazInput.vue.vue'
import { default as MazInputPrice } from './MazInputPrice.vue.vue'
import { default as MazLazyImg } from './MazLazyImg.vue.vue'
import { default as MazPhoneNumberInput } from './MazPhoneNumberInput.vue.vue'
import { default as MazSelect } from './MazSelect.vue.vue'
import { default as MazSpinner } from './MazSpinner.vue.vue'
import { default as MazTransitionExpand } from './MazTransitionExpand.vue.vue'

export {
  MazArrowIcon,
  MazAvatar,
  MazBackDrop,
  MazBottomSheet,
  MazBtn,
  MazCard,
  MazCheckbox,
  MazDialog,
  MazDropzone,
  MazGallery,
  MazIcon,
  MazInput,
  MazInputPrice,
  MazLazyImg,
  MazPhoneNumberInput,
  MazSelect,
  MazSpinner,
  MazTransitionExpand,
}

export default {
  MazArrowIcon,
  MazAvatar,
  MazBackDrop,
  MazBottomSheet,
  MazBtn,
  MazCard,
  MazCheckbox,
  MazDialog,
  MazDropzone,
  MazGallery,
  MazIcon,
  MazInput,
  MazInputPrice,
  MazLazyImg,
  MazPhoneNumberInput,
  MazSelect,
  MazSpinner,
  MazTransitionExpand,
}
