name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: LouisMazel/repo
          TARGET_BRANCH: master
          BUILD_SCRIPT: make install-docs && make build-docs
          BUILD_DIR: packages/docs/docs/.vuepress/dist
