name: Build Tests
on:
  pull_request:
    branches: [master]
    paths:
      - "packages/docs/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install all dependencies
        run: make install
      - name: Build lib
        run: make build-lib
      - name: Build docs
        run: make build-docs
