name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install docs dependencies
        run: make install-docs
      - name: Build docs
        run: make build-docs

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: LouisMazel/repo
          TARGET_BRANCH: master
          BUILD_DIR: packages/docs/docs/.vuepress/dist
